### ISSUE TITLE
Support Driver (Code) version control

### ISSUE THREAD

**Issue by uMartinXu** [kubernetes-sigs/kernel-module-management#114]
### Issue Summary:
KMMO should support the scenario of driver (code) version upgrading.
### Suggested Priority(P1-P3) & Urgent(Urgent, medium, Low):
P1 & Urgent
### Issue Detail:
For the OOT(OutOfTree) Driver, the Driver(code) version might kept upgrading for adding new feature or bug fixing. So KMMO should support the upgrading of driver version to automatically (build and) upgrade kernel version according to user's configuration.

For Pre-build mode when the pre-build and released OOT driver container images are used, the KMMO should check whether there is a new released(latest) driver image can be used and upgrade the existing driver according to user's configuration. If there are several OOT driver version images exists, the latest (or the specific) version of driver container images can be deployed according to user's configuration.

For on-promise build mode it also can pick up the proper version (or latest) driver source from repo to build driver and package the driver binaries into the driver container image with the proper name and version.

### Solution Proposal
Let's start from the OOT driver image name and version control. Below Name Patten is recommended. 
`DriverName:DriverVersion-KernelVersion(-MachineType)`
Machine Type is optional If only single Machine Type is supported.
Using KMMO existing regexp and $KERNEL_FULL_VERSION variable mechanism, KMMO can find the proper driver container image for specific machine type and kernel version. 
Adding the DriverVersion into the Name Patten, KMMO can find the proper driver version according to user's configuration. 
In order to achieve this goal,

1.  A new variable $MODULE_VERSION need to be introduced into KMMO​
2. $MODULE_VERSION should be acquired from the driver project git hub Tags by KMMO​
3. MODULE_PROJECT_URL Primitive should be introduced into module CRD for KMMO for user to input the URL of the driver project​
4. MODULE_VERSION primitive should be introduced into module CRD for user to select to use the Latest or specific Version of driver ​
5. in on-premise build mode the Proper driver version code in the specified DRIVER_VERSION (this can be secured when we decouple the building process from module CRD yamal)​
6. KMMO should automatically upgrade the driver image if user uses latest driver release

### Example:
```
Module CR Yaml
spec:
  moduleVersion: Latest
  moduleProjectURL: https://github.com/intel/dgpu
...
kernelMappings:
        - regexp: '^.*\.x86_64$'
        containerImage: quay.io/ocpeng/intel-dgpu-driver-container:$MODUEL_VERSION-$KERNEL_FULL_VERSION
...
```
For this example, KMMO will always use the latest version of driver code to build the driver container image in on-premise mode; in pre-build mode, it will always find the latest version of prebuild driver container image with the proper kernel version. And the Module Version should acquired by KMMO from the tags of moduleProjetURL: https://github.com/intel/dgpu.

```
Module CR Yaml
spec:
  moduleVersion: 0.1
  moduleProjectURL: https://github.com/intel/dgpu
...
kernelMappings:
        - regexp: '^.*\.x86_64$'
        containerImage: quay.io/ocpeng/intel-dgpu-driver-container:$MODUEL_VERSION-$KERNEL_FULL_VERSION
...
```
For this example, KMMO will always use the 0.1 version of driver code to build the driver container image in on-premise mode; in pre-build mode, it will always find the 0.1 version of prebuild driver container image with the proper kernel version. And the Module Version should acquired by KMMO from the tags of moduleProjetURL: https://github.com/intel/dgpu.

### Subtasks
Obviously, it is a big task and we should split it into several sub tasks to discuss and track

- [ ] Mulitple version of prebuild driver container image support
- [ ] safely remove of the driver container image/kernel module
- [ ] Seamless upgrade supporting see (seamless upgrading)[https://sdk.operatorframework.io/docs/overview/operator-capabilities/#level-2---seamless-upgrades]
- [ ] Build the version of the module specified by user
- [ ] Auto build on the new/latest released module

**Comment by uMartinXu** [comment]
@qbarrand any comments? : )

**Comment by yevgeny-shnaidman** [comment]
@uMartinXu i think that letting KMMO periodically monitor github or image repository should not be KMM responsibility. Aside from configuration issues, it will be also dangerous, since it means that kernel modules will be updated without any changes to Modules CRs, which goes against kubernetes operator flow.  Also it means that, for example, a commit into github, will cause a change on the running cluster, without customer intervention/knowledge.
I think that adding additional substitution variable to spec is a good idea, and we need to discuss which variable needs to be added and supported.
@bthurber pre-flight is dealing with cluster upgrade situation. Here @uMartinXu  is talking about driver code upgrade, without cluster upgrade

**Comment by uMartinXu** [comment]
@yevgeny-shnaidman in general, I understand your concern. And I think we agree on the approach in example2, It is a good first step for us to go.
So as to the latest version support in example1, if it combines with the Canary deployment and testing process. It is safe and under control. At least, the operator needs a mechanism to inform users when there is a newer (latest) driver available either it is released as source code or released as the prebuild driver container image.

**Comment by uMartinXu** [comment]
> since it means that kernel modules will be updated without any changes to Modules CRs, which goes against kubernetes operator flow. 
@yevgeny-shnaidman I'd like to know more detail about the operator flow you mentioned, Could you please point me the link please.

>  Also it means that, for example, a commit into github, will cause a change on the running cluster
If a user is using on-promise build mode, I don't think every commit should trigger the building, only the official release cutting should trigger the build. of course that need the github project follow the proper releasing process to properly cut the release
But for the pre-build mode when there are new driver container images released, the operator should inform user about that release at least using some mechanism. If the user choses to use latest, together with the canary deployment and testing it is quite convenient for user.
