### ISSUE TITLE
Implement worker Pods

### ISSUE THREAD

**Issue by qbarrand** [kubernetes-sigs/kernel-module-management#468]
Implement worker Pods per the proposal presented at the 2023-07-12 community sync.
- [slides](https://docs.google.com/presentation/d/1NWDycIXcCLTjtrt2Xc_T7oXM8xBsVJuVkqXbMJBP_Fs/edit?usp=sharing)
```[tasklist]
### Tasks
- [ ] https://github.com/kubernetes-sigs/kernel-module-management/issues/474
- [ ] https://github.com/kubernetes-sigs/kernel-module-management/issues/467
- [ ] https://github.com/kubernetes-sigs/kernel-module-management/issues/466
- [ ] https://github.com/kubernetes-sigs/kernel-module-management/issues/469
- [ ] https://github.com/kubernetes-sigs/kernel-module-management/issues/472
- [ ] https://github.com/kubernetes-sigs/kernel-module-management/issues/479
- [ ] https://github.com/kubernetes-sigs/kernel-module-management/issues/509
- [ ] https://github.com/kubernetes-sigs/kernel-module-management/issues/512
```
