### ISSUE TITLE
Create the KMM worker application

### ISSUE THREAD

**Issue by qbarrand** [kubernetes-sigs/kernel-module-management#469]
```[tasklist]
### Tasks
- [ ] https://github.com/kubernetes-sigs/kernel-module-management/issues/470
- [ ] https://github.com/kubernetes-sigs/kernel-module-management/issues/471
- [ ] https://github.com/kubernetes-sigs/kernel-module-management/issues/490
- [ ] https://github.com/kubernetes-sigs/kernel-module-management/issues/492
- [ ] https://github.com/kubernetes-sigs/kernel-module-management/issues/493
- [ ] https://github.com/kubernetes-sigs/kernel-module-management/issues/538
```
