### ISSUE TITLE
v2.1 refactoring

### ISSUE THREAD

**Issue by qbarrand** [kubernetes-sigs/kernel-module-management#603]
- [ ] https://github.com/kubernetes-sigs/kernel-module-management/pull/602#discussion_r1356908331
- [ ] https://github.com/kubernetes-sigs/kernel-module-management/pull/602#discussion_r1357271309
- [ ] https://github.com/kubernetes-sigs/kernel-module-management/pull/602#discussion_r1357273992

```[tasklist]
### Tasks
- [ ] #340
- [ ] #507
- [ ] Deprecate the ModuleLoader ImagePullPolicy field
- [ ] https://github.com/kubernetes-sigs/kernel-module-management/issues/506
- [ ] https://github.com/kubernetes-sigs/kernel-module-management/issues/408
```
